"use client"

import { useState } from "react"
import { Sparkles, ChevronDown, ChevronUp } from "lucide-react"
import type { Email } from "@/lib/types"

interface AiSummaryProps {
  email: Email
}

export default function AiSummary({ email }: AiSummaryProps) {
  const [expanded, setExpanded] = useState(true)

  // In a real implementation, this would be generated by the AI SDK
  const summary =
    "This email contains a Q2 marketing campaign update. Key points: several milestones achieved, metrics and KPIs to review by Friday, and a team review meeting planned for next week."

  return (
    <div className="bg-primary-50 rounded-lg p-4 mb-6 border-l-4 border-primary">
      <div className="flex items-center justify-between cursor-pointer" onClick={() => setExpanded(!expanded)}>
        <div className="flex items-center text-sm font-semibold text-primary">
          <Sparkles className="h-4 w-4 mr-1.5" />
          AI SUMMARY
        </div>
        <button className="text-primary">
          {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
        </button>
      </div>

      {expanded && <div className="mt-2 text-sm">{summary}</div>}
    </div>
  )
}

